/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedTopUpRouteImport } from './routes/_authenticated/top-up'
import { Route as AuthenticatedReferencesRouteImport } from './routes/_authenticated/references'
import { Route as AuthenticatedProjectRouteImport } from './routes/_authenticated/project'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAutoUploaderRouteImport } from './routes/_authenticated/auto-uploader'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopUpRoute = AuthenticatedTopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferencesRoute = AuthenticatedReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectRoute = AuthenticatedProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoUploaderRoute =
  AuthenticatedAutoUploaderRouteImport.update({
    id: '/auto-uploader',
    path: '/auto-uploader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auto-uploader': typeof AuthenticatedAutoUploaderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project': typeof AuthenticatedProjectRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/top-up': typeof AuthenticatedTopUpRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auto-uploader': typeof AuthenticatedAutoUploaderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project': typeof AuthenticatedProjectRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/top-up': typeof AuthenticatedTopUpRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auto-uploader': typeof AuthenticatedAutoUploaderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/project': typeof AuthenticatedProjectRoute
  '/_authenticated/references': typeof AuthenticatedReferencesRoute
  '/_authenticated/top-up': typeof AuthenticatedTopUpRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auto-uploader'
    | '/dashboard'
    | '/project'
    | '/references'
    | '/top-up'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auto-uploader'
    | '/dashboard'
    | '/project'
    | '/references'
    | '/top-up'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auto-uploader'
    | '/_authenticated/dashboard'
    | '/_authenticated/project'
    | '/_authenticated/references'
    | '/_authenticated/top-up'
    | '/_authenticated/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top-up': {
      id: '/_authenticated/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof AuthenticatedTopUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references': {
      id: '/_authenticated/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof AuthenticatedReferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project': {
      id: '/_authenticated/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AuthenticatedProjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-uploader': {
      id: '/_authenticated/auto-uploader'
      path: '/auto-uploader'
      fullPath: '/auto-uploader'
      preLoaderRoute: typeof AuthenticatedAutoUploaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutoUploaderRoute: typeof AuthenticatedAutoUploaderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectRoute: typeof AuthenticatedProjectRoute
  AuthenticatedReferencesRoute: typeof AuthenticatedReferencesRoute
  AuthenticatedTopUpRoute: typeof AuthenticatedTopUpRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutoUploaderRoute: AuthenticatedAutoUploaderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectRoute: AuthenticatedProjectRoute,
  AuthenticatedReferencesRoute: AuthenticatedReferencesRoute,
  AuthenticatedTopUpRoute: AuthenticatedTopUpRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
