ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS error_status INTEGER,
  ADD COLUMN IF NOT EXISTS error_raw TEXT,
  ADD COLUMN IF NOT EXISTS fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS primary_provider TEXT,
  ADD COLUMN IF NOT EXISTS request_id TEXT;